#!/bin/bash -e

# Check if the user is root
if (( $(id -u) != 0 )); then
	echo "Bashshot must be run as root."
	exit 1;
fi

# cd to script dir
cd "$(dirname $0)"

# Gets date and filesystems (FS) from config file
. /usr/local/etc/bashshot.conf
date=$(date '+%Y-%m-%d_%H:%M')
logPath=/var/log/bashshot.log

# Decide which periods that is to be snapshoted
if [[ $frequent == "yes" ]]; then
	period="$period frequent"
fi
if [[ $hourly == "yes" && $(date '+%M') == "00" ]]; then
	period="$period hourly"
fi
if [[ $daily == "yes" && $(date '+%H:%M') == "00:00" ]]; then
	period="$period daily"
fi
if [[ $weekly == "yes" && $(date '+%u %H:%M') == "7 00:00" ]]; then
	period="$period weekly"
fi
if [[ $monthly == "yes" && $(date '+%d %H:%M') == "01 00:00" ]]; then
	period="$period monthly"
fi

# Echos stuff
echo ""
echo "Written by bashshot.sh"
echo "------------------------"
date "+%Y-%m-%d %H:%M"

#Loops through periods to run
for time in $period; do
	# Loops through FS to snapshot, but skip empty
	for fs in $filesystems;	do
		if [[ -n $time ]]
		then
			if zfs snapshot $fs@"$time"_"$date"; then
				echo "A $time snapshot of $fs taken."
			else
				echo "The taking of a $time snapshot of $fs FAILED!"
			fi
		fi
	done
done

echo "------------------------"

exit 0;
